version: 3

dotenv: ['.env']

tasks:
  compose:
    internal: true
    cmd: docker compose -f ./.sandbox/compose.yml --project-directory . {{.COMPOSE}}

  compose-exec:
    internal: true
    cmds:
      - task: compose
        vars:
          COMPOSE: exec --user {{.USER}} sandbox {{.COMMAND}}

  up:
    cmds:
      - task: compose
        vars:
          COMPOSE: up -d

  down:
    cmds:
      - task: compose
        vars:
          COMPOSE: down

  build:
    cmds:
      - task: compose
        vars:
          COMPOSE: build sandbox

  cleanup:
    cmds:
      - task: compose
        vars:
          COMPOSE: down --rmi all --volumes

  shell:
    aliases: [sh]
    cmds:
      - task: compose-exec
        vars:
          COMMAND: /bin/zsh

  shell-execute:
    aliases: [exec]
    cmds:
      - task: compose-exec
        vars:
          COMMAND: /bin/zsh -c "{{.CLI_ARGS}}"
