<?php

namespace Tests\Feature;

use App\Models\Flow;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\Schema;
use Inertia\Testing\AssertableInertia as Assert;
use Tests\TestCase;

class FlowGraphDefaultsTest extends TestCase
{
    use RefreshDatabase;

    public function test_cron_flow_is_created_without_flow_graph_columns(): void
    {
        /** @var User $user */
        $user = User::factory()->createOne();

        $this->actingAs($user)->post(route('flows.store'), [
            'name' => 'Morning flow',
            'description' => 'Daily cron scenario',
            'template' => 'cron',
            'timezone' => 'Europe/Berlin',
        ])->assertRedirect();

        $flow = Flow::query()
            ->where('user_id', $user->id)
            ->where('name', 'Morning flow')
            ->first();

        $this->assertNotNull($flow);
        $this->assertSame('Europe/Berlin', $flow->timezone);
        $this->assertNotNull($flow->code_updated_at);
        $this->assertFalse(Schema::hasColumn('flows', 'graph'));
        $this->assertFalse(Schema::hasColumn('flows', 'graph_generated_at'));
        $this->assertArrayNotHasKey('graph', $flow->getAttributes());
        $this->assertArrayNotHasKey('graph_generated_at', $flow->getAttributes());
    }

    public function test_flow_creation_uses_app_timezone_when_not_provided(): void
    {
        config(['app.timezone' => 'UTC']);

        /** @var User $user */
        $user = User::factory()->createOne();

        $this->actingAs($user)->post(route('flows.store'), [
            'name' => 'Fallback timezone flow',
            'description' => 'Fallback timezone scenario',
            'template' => 'blank',
        ])->assertRedirect();

        $flow = Flow::query()
            ->where('user_id', $user->id)
            ->where('name', 'Fallback timezone flow')
            ->first();

        $this->assertNotNull($flow);
        $this->assertSame('UTC', $flow->timezone);
    }

    public function test_flow_creation_rejects_invalid_timezone(): void
    {
        /** @var User $user */
        $user = User::factory()->createOne();

        $this->actingAs($user)
            ->from(route('flows.create'))
            ->post(route('flows.store'), [
                'name' => 'Invalid timezone flow',
                'description' => 'Should fail validation',
                'template' => 'cron',
                'timezone' => 'Invalid/Timezone',
            ])
            ->assertRedirect(route('flows.create'))
            ->assertSessionHasErrors(['timezone']);

        $this->assertDatabaseMissing('flows', [
            'user_id' => $user->id,
            'name' => 'Invalid timezone flow',
        ]);
    }

    public function test_show_uses_last_development_deployment_as_graph_source(): void
    {
        /** @var User $user */
        $user = User::factory()->createOne();

        $flow = Flow::factory()->forUser($user)->createOne([
            'name' => 'Legacy cron flow',
            'code' => <<<'PY'
from kawa import actor, Context, Cron


@actor(receivs=Cron.by("0 8 * * *"))
def MorningActor(ctx: Context, event):
    print("Good morning!")
PY,
        ]);

        $run = $flow->runs()->create([
            'type' => 'development',
            'active' => false,
            'status' => 'stopped',
            'started_at' => now()->subMinute(),
            'finished_at' => now(),
            'code_snapshot' => $flow->code,
            'graph_snapshot' => [
                'nodes' => [
                    ['id' => 'Cron', 'type' => 'event', 'label' => 'Cron'],
                    ['id' => 'MorningActor', 'type' => 'actor', 'label' => 'MorningActor'],
                ],
                'edges' => [
                    ['from' => 'Cron', 'to' => 'MorningActor'],
                ],
            ],
        ]);

        $this->actingAs($user)
            ->get(route('flows.show', $flow))
            ->assertOk()
            ->assertInertia(fn (Assert $page) => $page
                ->component('flows/Editor')
                ->where('lastDevelopmentDeployment.id', $run->id)
                ->where('lastDevelopmentDeployment.graph.nodes.0.id', 'Cron')
                ->where('lastDevelopmentDeployment.graph.edges.0.from', 'Cron')
                ->where('lastDevelopmentDeployment.graph.edges.0.to', 'MorningActor')
            );
    }

    public function test_update_ignores_legacy_graph_payload_and_tracks_code_update_time(): void
    {
        /** @var User $user */
        $user = User::factory()->createOne();

        $flow = Flow::factory()->forUser($user)->createOne([
            'name' => 'Readonly graph flow',
            'description' => 'Graph should be generated by runtime only',
            'code' => 'print("old")',
            'code_updated_at' => now()->subHour(),
        ]);

        $previousCodeUpdatedAt = $flow->code_updated_at;

        $this->actingAs($user)
            ->put(route('flows.update', $flow), [
                'name' => 'Readonly graph flow',
                'description' => 'Graph should be generated by runtime only',
                'code' => 'print("new")',
                'graph' => [
                    'nodes' => [
                        ['id' => 'user_defined_node'],
                    ],
                    'edges' => [
                        ['from' => 'user_defined_node', 'to' => 'other'],
                    ],
                ],
            ])
            ->assertRedirect(route('flows.show', $flow));

        $flow->refresh();

        $this->assertSame('print("new")', $flow->code);
        $this->assertNotNull($flow->code_updated_at);
        $this->assertNotNull($previousCodeUpdatedAt);
        $this->assertTrue($flow->code_updated_at->gt($previousCodeUpdatedAt));
        $this->assertArrayNotHasKey('graph', $flow->getAttributes());
        $this->assertArrayNotHasKey('graph_generated_at', $flow->getAttributes());
    }

    public function test_flow_update_rejects_invalid_timezone(): void
    {
        /** @var User $user */
        $user = User::factory()->createOne();

        $flow = Flow::factory()->forUser($user)->createOne([
            'timezone' => 'UTC',
        ]);

        $this->actingAs($user)
            ->from(route('flows.show', $flow))
            ->put(route('flows.update', $flow), [
                'name' => $flow->name,
                'description' => $flow->description,
                'code' => $flow->code,
                'timezone' => 'Invalid/Timezone',
            ])
            ->assertRedirect(route('flows.show', $flow))
            ->assertSessionHasErrors(['timezone']);

        $flow->refresh();

        $this->assertSame('UTC', $flow->timezone);
    }
}
