<?php

namespace Tests\Feature;

use App\Models\Flow;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Tests\TestCase;

class FlowGraphDefaultsTest extends TestCase
{
    use RefreshDatabase;

    public function test_cron_flow_is_created_with_empty_graph(): void
    {
        /** @var User $user */
        $user = User::factory()->createOne();

        $this->actingAs($user)->post(route('flows.store'), [
            'name' => 'Morning flow',
            'description' => 'Daily cron scenario',
            'template' => 'cron',
            'timezone' => 'Europe/Berlin',
        ])->assertRedirect();

        $flow = Flow::query()
            ->where('user_id', $user->id)
            ->where('name', 'Morning flow')
            ->first();

        $this->assertNotNull($flow);
        $this->assertSame(['nodes' => [], 'edges' => []], $flow->graph);
        $this->assertSame('Europe/Berlin', $flow->timezone);
        $this->assertNotNull($flow->code_updated_at);
    }

    public function test_flow_creation_uses_app_timezone_when_not_provided(): void
    {
        config(['app.timezone' => 'UTC']);

        /** @var User $user */
        $user = User::factory()->createOne();

        $this->actingAs($user)->post(route('flows.store'), [
            'name' => 'Fallback timezone flow',
            'description' => 'Fallback timezone scenario',
            'template' => 'blank',
        ])->assertRedirect();

        $flow = Flow::query()
            ->where('user_id', $user->id)
            ->where('name', 'Fallback timezone flow')
            ->first();

        $this->assertNotNull($flow);
        $this->assertSame('UTC', $flow->timezone);
    }

    public function test_flow_creation_rejects_invalid_timezone(): void
    {
        /** @var User $user */
        $user = User::factory()->createOne();

        $this->actingAs($user)
            ->from(route('flows.create'))
            ->post(route('flows.store'), [
                'name' => 'Invalid timezone flow',
                'description' => 'Should fail validation',
                'template' => 'cron',
                'timezone' => 'Invalid/Timezone',
            ])
            ->assertRedirect(route('flows.create'))
            ->assertSessionHasErrors(['timezone']);

        $this->assertDatabaseMissing('flows', [
            'user_id' => $user->id,
            'name' => 'Invalid timezone flow',
        ]);
    }

    public function test_show_does_not_backfill_graph_when_it_is_empty(): void
    {
        /** @var User $user */
        $user = User::factory()->createOne();

        $flow = Flow::factory()->forUser($user)->createOne([
            'name' => 'Legacy cron flow',
            'code' => <<<'PY'
from kawa import actor, Context
from kawa.cron import CronEvent


@actor(receivs=CronEvent.by("0 8 * * *"))
def MorningActor(ctx: Context, event):
    print("Good morning!")
PY,
            'graph' => ['nodes' => [], 'edges' => []],
        ]);

        $this->actingAs($user)
            ->get(route('flows.show', $flow))
            ->assertOk();

        $flow->refresh();

        $this->assertSame(['nodes' => [], 'edges' => []], $flow->graph);
    }

    public function test_update_ignores_graph_payload_and_tracks_code_update_time(): void
    {
        /** @var User $user */
        $user = User::factory()->createOne();

        $originalGraph = [
            'nodes' => [
                ['id' => 'initial_event', 'type' => 'event', 'label' => 'initial_event'],
            ],
            'edges' => [],
        ];

        $flow = Flow::factory()->forUser($user)->createOne([
            'name' => 'Readonly graph flow',
            'description' => 'Graph should be generated by runtime only',
            'code' => 'print("old")',
            'graph' => $originalGraph,
            'code_updated_at' => now()->subHour(),
        ]);

        $previousCodeUpdatedAt = $flow->code_updated_at;

        $this->actingAs($user)
            ->put(route('flows.update', $flow), [
                'name' => 'Readonly graph flow',
                'description' => 'Graph should be generated by runtime only',
                'code' => 'print("new")',
                'graph' => [
                    'nodes' => [
                        ['id' => 'user_defined_node'],
                    ],
                    'edges' => [
                        ['from' => 'user_defined_node', 'to' => 'other'],
                    ],
                ],
            ])
            ->assertRedirect(route('flows.show', $flow));

        $flow->refresh();

        $this->assertSame($originalGraph, $flow->graph);
        $this->assertSame('print("new")', $flow->code);
        $this->assertNotNull($flow->code_updated_at);
        $this->assertNotNull($previousCodeUpdatedAt);
        $this->assertTrue($flow->code_updated_at->gt($previousCodeUpdatedAt));
    }

    public function test_flow_update_rejects_invalid_timezone(): void
    {
        /** @var User $user */
        $user = User::factory()->createOne();

        $flow = Flow::factory()->forUser($user)->createOne([
            'timezone' => 'UTC',
        ]);

        $this->actingAs($user)
            ->from(route('flows.show', $flow))
            ->put(route('flows.update', $flow), [
                'name' => $flow->name,
                'description' => $flow->description,
                'code' => $flow->code,
                'timezone' => 'Invalid/Timezone',
            ])
            ->assertRedirect(route('flows.show', $flow))
            ->assertSessionHasErrors(['timezone']);

        $flow->refresh();

        $this->assertSame('UTC', $flow->timezone);
    }
}
